### ISSUE TITLE
Error when importing the package to Unity

### ISSUE THREAD

**Issue by waffwrw** [Lachee/discord-rpc-unity#11] opened 2023-08-09 19:55 UTC
I Get this error when I import the package from the the Unity Package Manager via Git URL

error CS1566: Error reading resource 'DiscordRPC.xml' -- 'Could not find a part of the path 'Packages\com.lachee.discordrpc\Runtime\DiscordRPC.xml'.'

**Comment by Lachee** [comment] 2023-08-10 05:46
Hello thanks for this issue. I have reproduced it and investigating it.

Can you give the unity version you're using ?

**Comment by waffwrw** [comment] 2023-08-10 11:30
I'm using Unity Version 2021.3.23f1

**Comment by waffwrw** [comment] 2023-08-19 21:58
are there any updates?

**Comment by Lachee** [comment] 2023-08-21 02:15
ah sorry been super busy last 2 weeks. I'll look into it today for you :)

**Comment by waffwrw** [comment] 2023-08-21 10:16
tysm!!

**Comment by Lachee** [comment] 2023-08-23 06:06
error closing. Didn't realise `fixes #issue` closed issues automagically

**Comment by Lachee** [comment] 2023-08-23 07:24
This has been resolved with [Release v1.1.1](https://github.com/Lachee/discord-rpc-unity/releases/tag/v1.1.1)

**Closed as completed by Lachee** 2023-08-23 07:24 UTC

**Comment by webik150** [comment] 2024-03-12 00:27
I still have an issue with this. Same error, only it doesn't necessarily appear when importing, rather once I compile my scripts (after any code change). From what I understand Unity deletes the file since it can't 

`error CS1566: Error reading resource 'DiscordRPC.xml' -- 'Could not find a part of the path 'C:\pathtoproject\Packages\com.lachee.discordrpc\Runtime\DiscordRPC.xml'.'`

I seem to have fixed this by manually creating the desired path and copying the files there (along with a .meta file from version 1.0.3).
